# Generated by Django 6.0 on 2026-01-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storygame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='storygame.title')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
