# Generated by Django 6.0 on 2026-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storygame', '0002_storypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='drawing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
