# Generated by Django 6.0 on 2026-01-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storygame", "0003_storypage_drawing"),
    ]

    operations = [
        migrations.AddField(
            model_name="storypage",
            name="narration",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storypage",
            name="narration_mime",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
